### ISSUE TITLE
Using dev mode with KV v1 by default

### ISSUE THREAD

**Issue by arossert** [hashicorp/docker-vault#111]
In the documentation it stated:

` when running a dev-mode server, the v2 kv secrets engine is enabled by default at the path secret/ `

Is it possible to start in dev mode with secrets engine v1 as default?
If no, how can I change the version from a custom Dockerfile?

**Comment by fewknow** [comment]
@arossert you can issue these commands to revert versions for your secrets.
		echo "setting up vault"
		vault secrets disable secret
		vault secrets enable -version=1 -path=secret -description=$SECRET_DESCRIPTION kv

Probably can just add them as RUN commands in docker file.

**Comment by arossert** [comment]
@fewknow Thanks for the fast replay.
I have already tried that like this:
```
FROM vault

ENV VAULT_ADDR="http://127.0.0.1:8200"

RUN vault secrets disable secret &&\
    vault secrets enable -path=secret kv
```
But when I try to build it with:
`docker build -f Dockerfile.vault-dev .`

I get this error:
`Error disabling secrets engine at secret/: Delete http://127.0.0.1:8200/v1/sys/mounts/secret: dial tcp 127.0.0.1:8200: connect: connection refused`

It seems like the vault is not runinig yet.

**Comment by joninvski** [comment]
@arossert it might not be the best way but i solved using this two files:

Dockerfile.vault-dev
```
FROM vault

RUN apk add --no-cache openssl
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

ENV VAULT_TOKEN=vaultDevToken
ENV VAULT_DEV_ROOT_TOKEN_ID=vaultDevToken
ENV VAULT_ADDR="http://127.0.0.1:8200"

COPY set_v1_secrets.sh /home/vault/

CMD ["/home/vault/set_v1_secrets.sh"]
```

set_v1_secrets.sh
```
#!/bin/sh

docker-entrypoint.sh server -dev &
dockerize -wait tcp://127.0.0.1:8200 -timeout 30s
vault secrets disable secret
vault secrets enable -version=1 -path=secret -description='local secrets' kv
```

hope this helps

**Comment by mrusanov** [comment]
@arossert I have a little bit of a hacky solution, but it works perfectly for me. I am using the Docker health check to execute the commands that will switch the version of the kv from 2 to 1. Check the **docker-compose** snippet below:

```
services:
...
  vault:
    image: vault
    cap_add:
        - IPC_LOCK
    environment:
        VAULT_ADDR: "http://192.168.99.100:8200"
        VAULT_DEV_ROOT_TOKEN_ID: "vault-demo-token"
    ports:
        - "8200:8200"
    healthcheck:
      test: "vault login vault-demo-token &&
             vault kv get secret &&
             vault secrets disable secret &&
             vault secrets enable -version=1 -path=secret kv"
      interval: 5s
...
```
The whole magic is in the **healthcheck** section. On every 5 seconds:
1) Login on **vault**, using the **VAULT_DEV_ROOT_TOKEN_ID**.
2) Check if the version of KV is 2. I try to execute a non-listing operation `vault kv get secret` on the root of the **secret** mount, which is not supported by KV v2 (this command should fail with: **_Non-listing operations on the root of a K/V v2 mount are not supported._**)!
3) Unmount the **secret** kv.
4) Mount the **secret** kv, but this time with version 1.

Thanks to 2), the switch (steps 3 and 4) will happen only on the first health check. After that, on every 5 second, only a login and check will be done (steps 1 and 2).

**_Important note:_** The parameter **VAULT_ADDR** is needed if the vault server is not running on your local machine. In my case it is running on the Docker machine (192.169.99.100) and I should specify that, otherwise the commands in the health check will fail.

Hope it helps!
