### ISSUE TITLE
vault:1.5.4 (latest) does not start with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by mipnw** [hashicorp/docker-vault#198]
On AWS EKS v1.17.9-eks-4c6976, if you try to deploy vault:1.5.4 with 
```
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
     add: 
      - IPC_LOCK
```
the container fails to start with error 
```
Failed to set capabilities on file `/bin/vault' (Read-only file system)
```
even though it is Vault's security recommendation to have readonlyRootFilesystem, see https://learn.hashicorp.com/tutorials/vault/kubernetes-security-concerns?in=vault/kubernetes#don-t-run-as-root

Remove ` readOnlyRootFilesystem: true` from the security context, and it deploys fine.
