### ISSUE TITLE
Docker image has multiple issues that prevent it from being used out-of-the-box

### ISSUE THREAD

**Issue by gaballard** [hashicorp/docker-vault#39]
We're using `docker run` to start the image. Our Docker version is `17.03.01-ce`.

We get the following error:

    Couldn't start vault with IPC_LOCK. Disabling IPC_LOCK, please use --privileged or --cap-add IPC_LOCK

With all of the following `docker run` permutations:

- `docker run vault`
- `docker run vault --cap-add IPC_LOCK`
- `docker run vault --privileged`
- `docker run vault server`
- `docker run vault server --cap-add IPC_LOCK`
- `docker run vault server --privileged`

We then pulled the Vault Docker image locally. We set the `SKIP_SETCAP` env var to `1` and updated the `CMD` property at the end. We tried the following commands and received the following errors:

- Running the Docker image with `CMD` set to `["server"]`:

    Error initializing core: Failed to lock memory: cannot allocate memory

- Running the Docker image with `CMD` set to `["server", "--cap-add", "IPC_LOCK"]`:

    flag provided but not defined: -cap-add

- Running the Docker image with `CMD` set to `["vault", "server", "--cap-add", "IPC_LOCK"]`:

    flag provided but not defined: -cap-add

- Running the Docker image with `CMD` set to `["server", "--privileged"]`:

    flag provided but not defined: -privileged

- Running the Docker image with `CMD` set to `["vault", "server", "--privileged"]`:

    flag provided but not defined: -privileged

There are various closed GitHub issues regarding these problems and other tangential ones  - #24, #17, #18 - but none of those solutions apply to this situation (plus, they apply to an earlier version of the image, not 0.7.0). 

These issues have rendered this image useless for our team; we've begun rolling our own in the meantime.

**Comment by gaballard** [comment]
Update: We were able to get it running by using Kubernetes to run the Docker image. We created a Kubernetes deployment script as follows:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault
        imagePullPolicy: Always
        args: ["server"]
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        ports:
        - containerPort: 8200
```

(Kubernetes' `args` option overrides the Dockerfile's `CMD` property).

Hopefully this helps someone in the future!
