### ISSUE TITLE
Specifying listener in config file and -dev-listen-address leads to bind error

### ISSUE THREAD

**Issue by eyn** [hashicorp/docker-vault#7]
Using this docker-compose.yml file will repoduce:

```
vault:
  image: vault
  environment:
    VAULT_LOCAL_CONFIG: '{"backend": {"inmem": {}}, "listener": { "tcp": { "address": "0.0.0.0:8200", "tls_disable": 1 } }, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    VAULT_DEV_ROOT_TOKEN_ID: 'insecure-development-root-token'
    command: ['server', '-dev']
```

Running this gives the following output:
```
> docker-compose -f docker-compose/base.yml -f docker-compose/development.yml up vault
Recreating dockercompose_vault_1
Attaching to dockercompose_vault_1
vault_1         | Error initializing listener of type tcp: listen tcp 0.0.0.0:8200: bind: address already in use
dockercompose_vault_1 exited with code 1
```

output of uname -a:
```
>uname -a
Darwin MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

> docker-machine ssh default uname -a
Linux default 4.4.8-boot2docker #1 SMP Mon Apr 25 21:57:27 UTC 2016 x86_64 GNU/Linux
```

If I remove listener section from VAULT_LOCAL_CONFIG then I no longer get the error
```
vault:
  image: vault
  environment:
    VAULT_LOCAL_CONFIG: '{"backend": {"inmem": {}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    VAULT_DEV_ROOT_TOKEN_ID: 'insecure-development-root-token'
    command: ['server', '-dev']
```
