### ISSUE TITLE
Unable to initalise Vault - no decent error message to put here.

### ISSUE THREAD

**Issue by bweston92** [hashicorp/docker-vault#82]
As you can see in my attempt to initialise the Vault tool below you can see I have issues but no real error message.

```
$ vault operator init -address=http://127.0.0.1:8200
Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* failed to check for initialization: context deadline exceeded

```

This is a Docker Swarm deployment with the following:
```
version: '3.5'
services:
  vault:
    image: vault:0.9.5
    command: vault server -config /config.hcl
    configs:
      - source: vault_hcl
        target: /config.hcl
        mode: 0440
    environment:
      SKIP_SETCAP: "true"
    ports:
      - 8200:8200

configs:
  vault_hcl:
    file: ./config.hcl
```

./config.hcl
```
disable_mlock = true
default_lease_ttl = "168h"
max_lease_ttl = "720h"

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = true
}

storage "etcd" {
    address = "http://any_swarm_ip:2379"
    etcd_api = "v3"
}
```

Logs
```
vault_1  | ==> Vault server configuration:
vault_1  |
vault_1  |                      Cgo: disabled
vault_1  |               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "disabled")
vault_1  |                Log Level: info
vault_1  |                    Mlock: supported: true, enabled: false
vault_1  |                  Storage: etcd (HA disabled)
vault_1  |                  Version: Vault v0.9.5
vault_1  |              Version Sha: 36edb4d42380d89a897e7f633046423240b710d9
vault_1  |
vault_1  | ==> Vault server started! Log data will stream in below:
vault_1  |
vault_1  | 2018/03/08 11:33:35.916606 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
vault_1  | 2018/03/08 11:35:00.395117 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
vault_1  | 2018/03/08 11:39:14.567394 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
vault_1  | 2018/03/08 11:39:26.870346 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
vault_1  | 2018/03/08 11:44:39.518830 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
vault_1  | 2018/03/08 11:45:11.857957 [ERROR] core: barrier init check failed: error=failed to check for initialization: context deadline exceeded
```

I've `exec`'d the container pulled down `etcdctl` and tested I can do a `member list` and it works fine.

Any help would be appreciated :)
